### ISSUE TITLE
User class bad formatted method

### ISSUE THREAD

**Issue by David-Baron** [fatihemre/football-standings#6]
In User::class (who will be UserManager) the exist method code is:

```
public function exists($email, $password)
    {
        $sth = $this->connection->prepare("SELECT * FROM users WHERE email=:email");
        $sth->execute(['email'=>$email]);
        $sth->setFetchMode(\PDO::FETCH_CLASS, UserEntity::class);
        $user = $sth->fetch();

        return $user ? (password()->verify($user->password, $password) ? $user : false) : false;

    }
```

This method should return a boolean: exist? true : false 
and it will never be up to the manager to handle features like password verification.

**Comment by fatihemre** [comment]
You're right, i will be fixed.

**Comment by David-Baron** [comment]
@fatihemre You missed something important!

here:
```
$sth = $this->connection->prepare("SELECT * FROM users WHERE email=:email");
        $sth->execute(['email'=>$email]);
```
will be:

```
$sth = $this->connection->prepare("SELECT * FROM users WHERE email=:emai AND password=:passwordl");
        $sth->execute([':email' => $email, ':password' => $password]);
```

**Comment by fatihemre** [comment]
You can see the [Users Table](https://github.com/fatihemre/football-standings/blob/master/scheme/tables.sql#L48) Email column is already unique.

getUser method is fetching user information with email condition. [As you can see](https://github.com/fatihemre/football-standings/blob/master/app/Controller/AuthController.php#L33) we check the password in the controller

**Comment by David-Baron** [comment]
@fatihemre 
This table was not present when I downloaded the project.

Some things:

Why do you use: UNIQUE KEY `email_unique` (`email`) USING BTREE

Do you understand what is added when you have done this?

This is just a recommendation: stop naming the column display_someting, just name it something.

**Comment by fatihemre** [comment]
> 

Yes, i committed it 2 days ago, because of your [issue#4](https://github.com/fatihemre/football-standings/issues/4)

email column should be unique and i put a unique index with btree. Because btree is more useable than hash. You know btree is default. If you need more information please [click here](https://codeutility.org/mysql-b-tree-vs-hash-table-stack-overflow/)

And display_something is good for me. Because if you want to put full name or alias for teams to database you can add a new "name" column. For example:

- display_name : Besiktas (this will show on front)
- full_name: Besiktas Jimnastik Kulübü (You can put this data to table if you want)
- short_code: BJK

- display_name: Chelsea FC
- full_name: Chelsea Football Club
- short_code: CHE

I will use full_name in next step. I will create Team details page and i will use all these informations (head coach, stadium, players, etc.)

**Comment by David-Baron** [comment]
@fatihemre I think you don't realy know what is Bree and Hash and what impact they do in your database. Other thing : this use a KEY (or INDEX it's the same thing) . Read a good documentation about those things.

Naming display_something is a really bad think. You display only on page view. A column is only data.

in your example:
name = Chelsea FC

**Comment by fatihemre** [comment]
Okay @David-Baron what is your suggestion about Index?

**Comment by David-Baron** [comment]
@fatihemre It is used on 'big table' to favor the sql engine. Each KEY or INDEX you do doubles the weight of the table. Creating an index on a user table that only has 4 columns is useless.
The email column should just be:
```sql
`email` varchar(255) NOT NULL UNIQUE,
```
or (if your sql manager does not want it)
```sql
`email` varchar(255) NOT NULL,
...
UNIQUE (email)
```
